### PR TITLE
docs: update scaling doc with federated setup and troubleshooting chapter

### PR DESCRIPTION
**Pull request by andreasgerstmayr**

### CODE REVIEW

**Comment by natoscott** [comment]
LGTM.

**Comment by goodwinos** [comment]
Looks good Andreas - would it be worth adding a comparison between federated / non-federated results?

**Comment by andreasgerstmayr** [comment]
> Looks good Andreas - would it be worth adding a comparison between federated / non-federated results?

Yep, I was about to write a sentence like "The observed values of each individual pmlogger farm of the federated deployment are almost identical to a single pmlogger farm, rendering the PCP deployment horizontally scalable" but it sounds too cheesy - do you have any better suggestions? :smile: 

The observed values of a non-federated farm with 100 loggers vs each farm of the federated results are almost identical, except of the network bandwidth (noted with "The network bandwidth is higher due to the inter-node communication of the Redis cluster.").

**Comment by andreasgerstmayr** [comment]
I'll merge it for now, let's add any updates on a later commit.

**Pull request merged**
