### PR TITLE
pmdabcc: netproc: add command name to instance names

### LINKED ISSUE #1233: Consider tweaking BCC PMDA netproc instance names
BCC PMDA netproc module provides metric instances like:

```
bcc.proc.io.net.perpid.tcp.recv.calls
    inst [4328 or "4328"] value 11873
```

But elsewhere the name is fixed-length:

```
bcc.proc.io.total
    inst [0 or "vda::000441"] value 53248

proc.psinfo.oom_score
    inst [4328 or "004328 wget"] value 668
```

Otherwise this would be cosmetic but with tools like _pmrep(1)_ one can select instances with e.g. `-i '.*001234.*'` so that doesn't now work across all the above metrics.

This doesn't look like a major issue but perhaps something to consider whether this sort of consistency would be helpful.

Thanks.

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
Mimics proc PMDA's logic to cut the cmdline.

Resolves #1233

### CODE REVIEW

**Review by myllynen — APPROVED** [review]
LGTM, tested to work as expected.

Just two minor questions. I think get_cmdline(pid) could be called directly so would be perhaps a bit cleaner, or what do you think? Would it make sense to make get_cmdline available for all modules (although the method doesn't exactly return cmdline at the moment so could think renaming if doing so)?

**Comment by andreasgerstmayr** [comment]
Thanks for the suggestions! I've moved it to the base class now and renamed it accordingly (`get_instance_name_for_pid`).

**Comment by andreasgerstmayr** [comment]
> I think get_cmdline(pid) could be called directly so would be perhaps a bit cleaner, or what do you think?

Using `self.get_cmdline()` instad of `PCPBCCModule.get_cmdline()`? tbh I got confused and thought I need to use the class name for static methods, but looks like in Python I don't need to (it's required in other languages for static methods). I've updated it accordingly.

Or are you referring to something else?

**Comment by myllynen** [comment]
Yes, that's what I meant but I think even plain `get_cmdline(pid)` would be enough.

**Comment by andreasgerstmayr** [comment]
> Yes, that's what I meant but I think even plain `get_cmdline(pid)` would be enough.

This got me curious:
```
class Test:
    @staticmethod
    def a():
        print("a() called")

    def b(self):
        Test.a()
        self.a()
        a()

t = Test()
t.b()

$ python test.py
a() called
a() called
Traceback (most recent call last):
  File "/home/agerstmayr/redhat/dev/test.py", line 12, in <module>
    t.b()
  File "/home/agerstmayr/redhat/dev/test.py", line 9, in b
    a()
NameError: name 'a' is not defined
```

I'll merge the PR now, thanks for the review!

**Pull request merged**
