### PR TITLE
Added support for scientific notation for metric values in StatsD payloads

### PR DESCRIPTION
**Pull request by Erbenos**
+ ...and small fix for underflow detection

Payloads with values such as these are valid:
:+1:
```
test:1e1|g
test:+1e+1|g
test:-1e-1|g
test:1.1e1|g
```
These are not:
:-1:
```
test:-.2e2|g
test:.2e2|g
test:e2|g
test:2e2.2|g
```

### CODE REVIEW

**Comment by natoscott** [comment]
@Erbenos looks like something that would be good to test - can we extend the testsuite to exercise this change?

**Comment by Erbenos** [comment]
You are right, will do next. While working on this I noticed that with
statsd Makefile the rules for unit tests for parsers are gone, so will
probably add that and integrate those as well.

**Comment by natoscott** [comment]
> You are right, will do next. While working on this I noticed that with statsd Makefile the rules for unit tests for parsers are gone, so will probably add that and integrate those as well.

Oh, not gone - they reside in the PCP QA suite now - see test 1599.  You can run them (and all statsd tests) via:

```
$ cd qa
$ ./check -g pmda.statsd
```

**Comment by Erbenos** [comment]
The unit tests for parsers work differently then the e2e tests from 1599
(unless I am missing something)

They are defined in src/pmdas/statsd/src/parser-basic.c at bottom of the
file (same for parser-ragel.rl). Idea was to build the binary with those
test specific D flags and then check for their output.

**Comment by natoscott** [comment]
> The unit tests for parsers work differently than the e2e tests from 1599 (unless I am missing something). They are defined in src/pmdas/statsd/src/parser-basic.c at bottom of the file (same for parser-ragel.rl). Idea was to build the binary with those test specific D flags and then check for their output.

Ah yes, you're right - some makefile tweaks will be needed there then.

cheers.

**Comment by lzap** [comment]
Out of curiosity, do tests try to launch the agent both with regular and ragel parsers?

**Comment by Erbenos** [comment]
The tests in my pmdastatsd repo do (those in my PCP fork too), but those
don't contain scientific notation payload. The tests in main PCP repository
for statsd are non-existant as of now.
Ideally unit tests will be extended as well to include scientific notation
payload. There are no tests written for this as of now.

**Comment by lzap** [comment]
It works great on my development setup. I haven't done anything big, about 1k packets delivered and parsed. One nitpick tho, units do not seem to be reported correctly. Since statsd protocol is always in miliseconds, the agent should set the units correctly so PCP tools show it properly:

```
metric:    statsd.fm_rails_http_request_total_duration
host:      box.home.lan
semantics: instantaneous value
units:     none
samples:   all
full label for instance[0]: /percentile99::action=index::controller=hosts_controller
```

This only applies to counters and timings. For gauge the unit is really unknown as statsd does not provide much info about the metrics.

**Comment by Erbenos** [comment]
> It works great on my development setup. I haven't done anything big, about 1k packets delivered and parsed. One nitpick tho, units do not seem to be reported correctly. Since statsd protocol is always in miliseconds, the agent should set the units correctly so PCP tools show it properly:
> 
> ```
> metric:    statsd.fm_rails_http_request_total_duration
> host:      box.home.lan
> semantics: instantaneous value
> units:     none
> samples:   all
> full label for instance[0]: /percentile99::action=index::controller=hosts_controller
> ```
> 
> This only applies to counters and timings. For gauge the unit is really unknown as statsd does not provide much info about the metrics. Do you want me to report a bug/issue?

Fixed in 8fcd8b9

**Pull request merged**
