### PR TITLE
pmdabpftrace: move example autostart scripts to /usr/share

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
Resolves: #1418

Got it working, until I found this age-old bug in rpm (open since  2008) which prevents rpm from replacing a directory with a symlink during upgrades: https://bugzilla.redhat.com/show_bug.cgi?id=447156
There is a workaround involving lua code in the `%pretrans` scriptlet: https://docs.fedoraproject.org/en-US/packaging-guidelines/Directory_Replacement/

@natoscott: what do you recommend, should I go down this path?

Alternatively I could make the bpftrace PMDA look into both directories, and implement some logic to not load the same script twice. I'll still move the default scripts to `/usr/share/pcp/pmdas/bpftrace/example`, but I won't replace the `/var/lib/pcp/pmdas/bpftrace/autostart` directory with a symlink, due to this rpm bug.

Not sure what's the best, I'm not 100% happy with either.

### CODE REVIEW

**Comment by natoscott** [comment]
> @natoscott: what do you recommend, should I go down this path?

I'd prefer not, it looks like a maintenance headache longer term.

> Alternatively I could make the bpftrace PMDA look into both directories

I think that's a good option.  Maybe it can be simpler still (since its a breaking v6 change already IIRC?) such that if the /etc path exists, we use that and stop looking further.  And in v6 we could stop installing the /var autostart location altogether, so that time people will have to migrate to the correct location and we don't end up with long-term path confusion for users.

**Comment by andreasgerstmayr** [comment]
> since its a breaking v6 change already IIRC?

Partly, yes - I plan to move the default scripts to the `/usr/share/` example folder, so by default no script will be started when the PMDA is started. This way people who don't want these default scripts don't get irritated when they delete them and they re-appear again for every PCP update.

There is another part to backwards compatibility, namely people who already have custom scripts in their `/var` autostart location and people who follow already published guides like https://www.redhat.com/en/blog/visualizing-system-performance-rhel-8-part-3-kernel-metric-graphing-performance-co-pilot-grafana-and-bpftrace

**Comment by andreasgerstmayr** [comment]
Updated PR to scan both directories. Duplicate scripts won't be started. This keeps backwards compatibility with user-provided scripts in `/var` and with guides mentioning this path.

**Review by natoscott — APPROVED** [review]
Makes sense, I think your most recent approach is the best so far.  Hadn't thought of the published guides, so yeah - it'd be good not to break that you're right.

**Pull request merged**
