### PR TITLE
Add hv_24x7 nest events to perfevent-pmda

### PR DESCRIPTION
**Pull request by anjutsudhakar**

### CODE REVIEW

**Comment by natoscott** [comment]
@anjutsudhakar hi Anju!  this change seems to be causing a build failure below qa/ (you'll be able to reproduce this by running make below qa/ - or using ./Makepkgs).  Also, could the tests could be updated to provide coverage of this new functionality?  (see below qa/perfevent)

gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fno-strict-aliasing -D_GNU_SOURCE  -Wall -O2 -g -DPCP_VERSION=\"4.2.0\" -I./src/include -I./src/include/pcp -fPIC -fno-strict-aliasing -D_GNU_SOURCE  -Wall -O2 -g -DPCP_VERSION=\"4.2.0\" -I../src/include -I../src/include/pcp -fPIC -fno-strict-aliasing -D_GNU_SOURCE -I../../src/pmdas/perfevent -DFILESYSTEM_ROOT='"./fakefs/"' -Wall -O2 -g -DPCP_VERSION=\"4.2.0\" -I../../src/include -I../../src/include/pcp --coverage -c -o target/gcov/architecture.o ../../src/pmdas/perfevent/architecture.c
perf_event_test.c: In function 'test_init_dynamic_events':
perf_event_test.c:707:5: error: too few arguments to function 'init_dynamic_events'
     init_dynamic_events(&pmu_list);
     ^~~~~~~~~~~~~~~~~~~
In file included from perf_event_test.c:12:
../../src/pmdas/perfevent/parse_events.h:86:5: note: declared here
 int init_dynamic_events(struct pmu **pmu_list, struct pmcsetting *dynamicpmc);
     ^~~~~~~~~~~~~~~~~~~
perf_event_test.c: In function 'test_minimum_dynamic_events':
perf_event_test.c:749:5: error: too few arguments to function 'init_dynamic_events'
     init_dynamic_events(&pmu_list);
     ^~~~~~~~~~~~~~~~~~~
In file included from perf_event_test.c:12:
../../src/pmdas/perfevent/parse_events.h:86:5: note: declared here
 int init_dynamic_events(struct pmu **pmu_list, struct pmcsetting *dynamicpmc);
     ^~~~~~~~~~~~~~~~~~~
perf_event_test.c: In function 'test_dynamic_events_fail_event':
perf_event_test.c:773:5: error: too few arguments to function 'init_dynamic_events'
     init_dynamic_events(&pmu_list);
     ^~~~~~~~~~~~~~~~~~~

**Comment by anjutsudhakar** [comment]
@natoscott Hi Nathan, Thanks for pointing this. I will fix this.

**Comment by natoscott** [comment]
> @natoscott Hi Nathan, Thanks for pointing this. I will fix this.

No problem - let me know if any help is needed.

**Comment by natoscott** [comment]
This PR was superceded by another, closing.

**Pull request closed without merging**
