### PR TITLE
pcp uag book - improved diagrams

### PR DESCRIPTION
**Pull request by arzoo14**
This PR improves all the diagrams of Performance Co-Pilot User's and Administrator's Guide book.

### CODE REVIEW

**Comment by natoscott** [comment]
> This PR improves all the diagrams of Performance Co-Pilot User's and Administrator's Guide book.

@arzoo14 thanks.  Can you give a summary of the changes?  From what I can see there are now drop-shadows and several other little improvements - could you list them out explicitly?

One thing I'd like to see is a bit of colour, and less black-and-white - without going crazy.  It'd be good to introduce colour and ensure a consistent font is used throughout, that will match with the colours and fonts used on the pcp.io website.  You'll want to create a colour pallette based on the content there (see the pcp-website git repo).

Maybe also do further research into tips for good technical diagrams, eg https://creately.com/blog/diagrams/create-awesome-diagrams/

**Comment by arzoo14** [comment]
> @arzoo14 thanks. Can you give a summary of the changes? From what I can see there are now drop-shadows and several other little improvements - could you list them out explicitly?
> 
> One thing I'd like to see is a bit of colour, and less black-and-white - without going crazy. It'd be good to introduce colour and ensure a consistent font is used throughout, that will match with the colours and fonts used on the pcp.io website. You'll want to create a colour pallette based on the content there (see the pcp-website git repo).
> 
> Maybe also do further research into tips for good technical diagrams, eg https://creately.com/blog/diagrams/create-awesome-diagrams/

@natoscott Following changes are made in the figures (in this PR):
1. Shadow of the shapes.
2. Color/font as per pcp.io website.
3. Proper Scaling.
4. Consistency (same font, same font size, same color palette, same size of the shapes) throughout the figures.
5. Improvements in arrow heads.

**Comment by natoscott** [comment]
@arzoo14 thanks for those notes and the introduction of colour looks good!

The font seems to be different to that we've used throughout the pcp.io website though - can you match that up?  It will be somewhere in the github.com/performancecopilot/pcp-website.git repo, below the 'assets' directory from memory - assets/css/libs/_settings.scss looks like the source of truth?

It'd be worth going through the contents of the 'stock-images' directory there too - that's another source of images we'll want to keep in-sync, and consistent with the overall pallette.

**Comment by arzoo14** [comment]
@natoscott 
I have made the requested changes.
Closing this in #1142

**Pull request closed without merging**
