### PR TITLE
golang: add initial PMAPI support

### PR DESCRIPTION
**Pull request by ryandoyle**
Adds initial golang support for PMAPI.

### CODE REVIEW

**Comment by ryandoyle** [comment]
Hey there - I had this sitting around in my local branch of PCP for a while.

There is still a bit of functionality missing from the PMAPI but there is more than enough to query for metrics/units/etc... I pulled this code from my simplified golang based interface to PCP  https://github.com/ryandoyle/pcpeasygo. Let me know if the licensing is okay (MIT).

**Comment by natoscott** [comment]
@ryandoyle in terms of language, build system, CI, and so on, this seems like it would be a better match for merging with Speed (https://github.com/performancecopilot/speed) rather than core PCP ...?  (Speed also happens to be MIT licensed as well).  Or perhaps as a standalone project building on PCP.

**Comment by ryandoyle** [comment]
Hey @natoscott. Fair enough - it might make including it in projects easier too. How about a separate repository and keep Speed standalone as it is?

What would you like the repository to be? `pcp-go`, `pmapi-go`, something else?

**Comment by natoscott** [comment]
| How about a separate repository and keep Speed standalone as it is?

Sounds fine to me.

| What would you like the repository to be?

I'd recommend a name that suits expansion beyond just PMAPI (so not "pmapi-go") - some of the code will be common for the PMDA API, which might be a follow-on project for you/someone, so best to not lock it into just the PMAPI (IMO).

So, "pcp-go" would be my choice of those two you suggested, or something else entirely - might want to think about when its being promoted and discussed, something catchy / recognisable like "Vector" or "Parfait" really helps.

I recommend we add it as a top-level project under the pcp github org though, to help get it visible - all up to you as the author, just let me know what you decide.

**Comment by ryandoyle** [comment]
Hey @natoscott, I'm happy with `pcp-go` as it's really just go bindings for PCP and not a new product like Vector or Parfait IMO.

Having it on the top-level PCP github org would be good as you've mentioned. I don't have access to do that, if yourself or someone else could that would be great.

Cheers - Ryan

**Comment by natoscott** [comment]
@ryandoyle yep, np - do you have a standalone git repo with this code?  (i.e. not part of a PCP repo with all of the PCP history).  If not, this can be cleanly extracted ... let's chat on slack tomorrow.

**Comment by ryandoyle** [comment]
@natoscott, yep I can extract my commits and push them standalone so thats all good.

**Comment by natoscott** [comment]
@ryandoyle ok mate, once you have a clean pcp-go repo, send me a pointer and I'll set it all up with you as owner, permissions to run CI, etc.

**Comment by ryandoyle** [comment]
Hey @natoscott, I've setup https://github.com/ryandoyle/pcp-go as what I'd push to the one under the pcp org. Let me know if it needs adjustments etc..

**Comment by ryandoyle** [comment]
Now at https://github.com/performancecopilot/pcp-go

**Pull request closed without merging**
