### PR TITLE
Add NFSv42 ops to linux PMDAs

### PR DESCRIPTION
**Pull request by jumitche**
I was taking a look at the NFS support in PCP and noticed that it didn't include the NFSv42 ops for client or server, so I thought I should contribute them.

### CODE REVIEW

**Comment by lberk** [comment]
Hi Justin,

Thanks for throwing this together, looks good to me.  Would you happen
to have a /proc/self/mountstats file that can exercise the new
pmda.nfsclient metrics that you could sent along? (scrubbed if needed)

I'd like to throw together a qa test (or just extend 798) for these
added nfsclient metrics to accompany your commit.

Cheers,

Lukas

**Comment by jumitche** [comment]
An example that features the additional values, but alas they are all zeros
[mountstats.txt](https://github.com/performancecopilot/pcp/files/580764/mountstats.txt)

**Comment by lberk** [comment]
Hey Justin,

Justin Mitchell <notifications@github.com> writes:
> An example that features the additional values, but alas they are all zeros
> mountstats.txt

Heh, thanks, I had a similar mountstats file, was just hopeful you might
have one with 'real' values.  I'll tweak it as needed with dummy values
for qa purposes.

I've merged your patch in my tree and Mark should (hopefully) be pulling
it into master shortly!

Thanks for the patch!

Lukas

**Comment by natoscott** [comment]
This PR was merged in commit f0bb18fc1e8ec last November - not sure why it wasn't auto-closed by github, but closing now anyway.

**Pull request closed without merging**
