### PR TITLE
pcp2graphite: manual update; -r - pickleprotocol

### PR DESCRIPTION
**Pull request by test-account-0**
Connected to #66

### CODE REVIEW

**Comment by test-account-0** [comment]
I haven't add version 3 (Python 3.0) and 4 (Python 3.4).

**Comment by test-account-0** [comment]
I probably should add some validation for this option.

**Comment by fche** [comment]
Explicit validation probably not necessary if python already throws an exception for invalid codes.

**Comment by dbrolley** [comment]
Merged a while ago. Now available in PCP release 3.11.1.

**Pull request closed without merging**
