### PR TITLE
Change the blank length of pmiostat's output

### PR DESCRIPTION
**Pull request by wuliming**

### CODE REVIEW

**Comment by lberk** [comment]
Hi, is there a particular reason for this output change?

The change also breaks qa 842 and 1099 (easy fix as it's simply whitespace), but it would be great to have a commit with those changes as well if there's a reason to update the blank length.

**Comment by goodwinos** [comment]
the timestamp printed with the -x t  option is 24 characters. So how come you want to change it to 28?

**Comment by wuliming** [comment]
Hi ：

I think the blank is too little(just one blank as follow) between  first column and second column.
# Timestamp              Device        rrqm/s  wrqm/s    r/s    w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await %util
Thu May  5 01:33:38 2016 sda              0.0     0.0    0.0    2.0      0.0      4.0     2.00     0.00     2.5     0.0     2.5   0.5

the timestamp printed with the -x t option is 24 characters. So how come you want to change it to 28?

**Comment by goodwinos** [comment]
On 05/05/2016 03:35 PM, wulm wrote:
> Hi ：
>
> I think the blank is too little(just one blank as follow) between first column and second column.
> # Timestamp Device rrqm/s wrqm/s r/s w/s rkB/s wkB/s avgrq-sz avgqu-sz await r_await w_await %util
> Thu May 5 01:33:38 2016 sda 0.0 0.0 0.0 2.0 0.0 4.0 2.00 0.00 2.5 0.0 2.5 0.5

well, the timestamp lines up with the timestamp column header, and the device name (sda in your example)
lines up with the 'Device' column header .. and space is rather precious in this report.

**Comment by lberk** [comment]
Closing due to inactivity, perhaps the spacing could be an argument to be specified/passed in the event there are alternate personal preferences.

**Pull request closed without merging**
