### PR TITLE
A couple of new pmmgr options

### PR DESCRIPTION
**Pull request by minnus**
hostid-static:
For when the host to be monitored doesn't know what it should be called.  Used in monitoring a VM farm where the name should be an externally generated uuid.

pmlogger-timefmt:
Allow the time format in the filename to be specified.

We have been running both of these for a while, and have seen no ill effects.

### CODE REVIEW

**Comment by fche** [comment]
LGTM generally; the "hostid-static" docs should disclose that setting it will force pmmgr to interpret -all- target pmcds it encounters as the same single static hostid, so this is only useful in a single-target configuration.

**Comment by minnus** [comment]
Thanks for the feedback Frank.  Should be addressed now.

With respect to the pmcd -H, I wasn't aware of that, and good to now know.  But in practice that would be cumbersome to implement in this specific environment.

**Comment by natoscott** [comment]
@minnus looks like these changes needs some automated QA?

**Comment by minnus** [comment]
OK, I think this should exercise the 2 new new options

**Pull request merged**
