### PR TITLE
pmdaproc: add acct metrics

### PR DESCRIPTION
**Pull request by shogo-matsumoto**
Collect accounting information from process accounting file (see acct(5)).
pmdaproc(acct) will try to read data from /var/account/pacct if it is effective,
or use private accounting file (/tmp/pcp-pacct).
Currently version 3 format (struct acct_v3) is available.

Related to https://github.com/performancecopilot/pcp/issues/922

### CODE REVIEW

**Comment by natoscott** [comment]
@shogo-matsumoto this is a looking good.  I've made some minor cleanups (see below), so I'll merge your current work (later today) so that we can work together on these remaining items ...

- hertz - use existing variable (I've fixed this one)
- configuration variables (intervals, file size thresholds, paths) - better if external configurable not hard-coded (handy for testing), and perhaps even could be modified using pmStore(3) and perhaps proc.control.acct or acct.control.* metrics.
- QA - sample pacct file (compressed) that we could temporarily put in /var/account/pacct to test the PMDA?
     - perhaps add this file (perhaps several, different / interesting cases?) to the qa/linux/ pre-installed files set
     - also need 'live' test to check metrics work with the running kernel process accounting
- code style differs to rest of pmdaproc?  best if its consistent
- path for PACCT_PCP_PRIVATE_FILE needs to be somewhere more private than /tmp for security (/var/lib/pcp/tmp/pmcd/proc-pacct? /var/lib/pcp/tmp is also PCP_TMPFILE_DIR)
- PACCT_SYSTEM_FILE should be from PCP_ACCT_DIR/pacct and configure.ac like PCP_SA_DIR
- file size is not an int (get_file_size) - use off_t or size_t or unsigned long long
- acct_debug always does the varargs expansion and always incurs function call overhead -
  maybe use __pmNotifyErr (gives timestamps) with DEBUG level and move pmDebugOptions check
  to wrap each callsite (lowest overhead).
- what is the permissions model going to be?  not yet using PCP per-context authentication ... I suggest we go with the model of no-authentication == no access like rest of proc.* metrics.

**Comment by natoscott** [comment]
@shogo-matsumoto correction:

>     * what is the permissions model going to be?  not yet using PCP per-context authentication ... I suggest we go with the model of no-authentication == no access like rest of proc.* metrics.

It *is* using per-context authentication, sorry, my mistake - although enforcing that only root can access these metrics values.  Should we allow any authenticated user, I wonder? (more like the proc.* metrics access)  If so, also the existing -A option to pmdaproc could be used to let a sysadmin allow all (incl. remote) access to the metrics, again consistent with proc.* metrics access.

```diff --git a/src/pmdas/linux_proc/pmda.c b/src/pmdas/linux_proc/pmda.c
index a100cc9e6..eb16153ba 100644
--- a/src/pmdas/linux_proc/pmda.c
+++ b/src/pmdas/linux_proc/pmda.c
@@ -1520,7 +1520,7 @@ proc_refresh(pmdaExt *pmda, int *need_refresh)
            refresh_cgroups2(cgroup, cgrouplen, need_refresh);
     }
 
-    if (need_refresh[CLUSTER_ACCT] && !proc_ctx_getuid(pmda->e_context))
+    if (need_refresh[CLUSTER_ACCT] && proc_ctx_getuid(pmda->e_context) >= 0)
        refresh_acct(&proc_acct);
 
     if (need_refresh[CLUSTER_PID_STAT] ||
```

Other items:
- selinux policy (I've started on this).
- man page updates for pmdaproc(1) to mention these metrics and the files used

If you want to chat directly to me about any of this (might be easier to coordinate our efforts that way?) please feel free to contact me on slack - access details on https://pcp.io/community.html

**Comment by shogo-matsumoto** [comment]
@natoscott 

Thank you so much for reviewing my code and merging it! I understand the remaining items. (I'm afraid my progress may be slow but) I'll start with the easier of tasks which remains unfinished. The following items seem relatively easy for me.

- configuration variables 
- code style
- PACCT_PCP_PRIVATE_FILE
- PACCT_SYSTEM_FILE 
- file size

>Should we allow any authenticated user, I wonder? (more like the proc.* metrics access) If so, also the existing -A option to pmdaproc could be used to let a sysadmin allow all (incl. remote) access to the metrics, again consistent with proc.* metrics access.

Yes, I should have added all_access(-A). To be honest, current my implementation is halfway. It prevents non-root user from triggering refresh_acct but not from fetching values. It means any user can access acct metrics if root user accesses acct metrics at the same time.
On second thought, it may be best to adopt no-authentication, as you commented first, in order to allow pmlogger service to collect acct metrics.

>If you want to chat directly to me about any of this (might be easier to coordinate our efforts that way?) please feel free to contact me on slack - access details on https://pcp.io/community.html

Thank you for the suggestion. I consider using slack. In most situations e-mail or gihub may be preferable for me in terms of doing my day job (and in terms of my english skill). But slack will be helpful to discuss about complicated items. Thanks a lot.

**Comment by natoscott** [comment]
@shogo-matsumoto sounds good - I'll focus on the QA and will merge that access control change.

**Comment by natoscott** [comment]
@shogo-matsumoto I made a series of updates and additions to this new code yesterday - if you could find some time to review them, that'd be fantastic.

I have a couple of questions still, things I don't understand fully:
- why is the etime (elapsed time) metric a float and not an unsigned integer like the other time metrics (utime and stime)?  or should all three by floating point values?
- we're multiplying the time metrics by 1000 (converting seconds to milliseconds) - could we not export them directly in units of seconds?  (is this related to the floating point issue above?)

Thanks!

**Comment by shogo-matsumoto** [comment]
@natoscott 

> I made a series of updates and additions to this new code yesterday - if you could find some time to review them, that'd be fantastic.

Thank you for updating the code. I’ll read it.

>why is the etime (elapsed time) metric a float and not an unsigned integer like the other time metrics (utime and stime)? or should all three by floating point values?

I used float for etime because ac_etime field of struct acct_v3 is declared as float. However, as you commented, I think all three values (etime, utime, stime) should be floating values. I found my mistake. comp_t type is encoded by encode_comp_t function in linux kernel. It should be decoded when we read acct_v3. I paste a draft of a fix in the bottom of this comment. Could you review it?

By the way, is PM_SEM_COUNTER in the following code appropriate? pmval does not show non-zero value for utime or stime if PM_SEM_COUNTER is used.

src/pmdas/linux_proc/pmda.c
```
    /* acct.psinfo.utime */
    { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_UTIME),
      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_MSEC,0) }, },
    /* acct.psinfo.stime */
    { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_STIME),
      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_MSEC,0) }, },
```

>we're multiplying the time metrics by 1000 (converting seconds to milliseconds) - could we not export them directly in units of seconds? (is this related to the floating point issue above?)

Yes, I should have used seconds (and float).

Thanks a lot,


draft of a fix:
```
diff --git a/src/pmdas/linux_proc/acct.c b/src/pmdas/linux_proc/acct.c
index 92ec79821..1841bec0e 100644
--- a/src/pmdas/linux_proc/acct.c
+++ b/src/pmdas/linux_proc/acct.c
@@ -82,6 +82,21 @@ get_end_time_v3(void *entry)
 	   (int)(((struct acct_v3 *)entry)->ac_etime / hz);
 }
 
+static unsigned long long 
+decode_comp_t(comp_t c)
+{
+    int exp;
+    unsigned long long val;
+
+    exp = (c >> 13) & 0x7;
+    val = c & 0x1fff;
+
+    while (exp-- > 0)
+	val <<= 3;
+
+    return val;
+}
+
 static int
 acct_fetchCallBack_v3(int item, void *p, pmAtomValue *atom)
 {
@@ -103,31 +118,31 @@ acct_fetchCallBack_v3(int item, void *p, pmAtomValue *atom)
 	atom->ul = acctp->ac_btime;
 	break;
     case ACCT_ETIME:
-	atom->f = acctp->ac_etime * 1000 / hz;
+	atom->f = acctp->ac_etime / hz;
 	break;
     case ACCT_UTIME:
-	atom->ul = acctp->ac_utime * 1000 / hz;
+	atom->f = decode_comp_t(acctp->ac_utime) * 1.0 / hz;
 	break;
     case ACCT_STIME:
-	atom->ul = acctp->ac_stime * 1000 / hz;
+	atom->f = decode_comp_t(acctp->ac_stime) * 1.0 / hz;
 	break;
     case ACCT_MEM:
-	atom->ul = acctp->ac_mem;
+	atom->ull = decode_comp_t(acctp->ac_mem);
 	break;
     case ACCT_IO:
-	atom->ul = acctp->ac_io;
+	atom->ull = decode_comp_t(acctp->ac_io);
 	break;
     case ACCT_RW:
-	atom->ul = acctp->ac_rw;
+	atom->ull = decode_comp_t(acctp->ac_rw);
 	break;
     case ACCT_MINFLT:
-	atom->ul = acctp->ac_minflt;
+	atom->ull = decode_comp_t(acctp->ac_minflt);
 	break;
     case ACCT_MAJFLT:
-	atom->ul = acctp->ac_majflt;
+	atom->ull = decode_comp_t(acctp->ac_majflt);
 	break;
     case ACCT_SWAPS:
-	atom->ul = acctp->ac_swaps;
+	atom->ull = decode_comp_t(acctp->ac_swaps);
 	break;
     case ACCT_EXITCODE:
 	atom->ul = acctp->ac_exitcode;
diff --git a/src/pmdas/linux_proc/pmda.c b/src/pmdas/linux_proc/pmda.c
index 82357243c..6b6f0185d 100644
--- a/src/pmdas/linux_proc/pmda.c
+++ b/src/pmdas/linux_proc/pmda.c
@@ -1427,31 +1427,31 @@ static pmdaMetric metrictab[] = {
       PM_TYPE_U32, ACCT_INDOM, PM_SEM_DISCRETE, PMDA_PMUNITS(0,1,0,0,PM_TIME_SEC,0) }, },
     /* acct.psinfo.etime */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_ETIME),
-      PM_TYPE_FLOAT, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_MSEC,0) }, },
+      PM_TYPE_FLOAT, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_SEC,0) }, },
     /* acct.psinfo.utime */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_UTIME),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_MSEC,0) }, },
+      PM_TYPE_FLOAT, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_SEC,0) }, },
     /* acct.psinfo.stime */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_STIME),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_MSEC,0) }, },
+      PM_TYPE_FLOAT, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,1,0,0,PM_TIME_SEC,0) }, },
     /* acct.psinfo.mem */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_MEM),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_INSTANT, PMDA_PMUNITS(1,0,0,PM_SPACE_KBYTE,0,0) }, },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_INSTANT, PMDA_PMUNITS(1,0,0,PM_SPACE_KBYTE,0,0) }, },
     /* acct.psinfo.io */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_IO),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
     /* acct.psinfo.rw */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_RW),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
     /* acct.psinfo.minflt */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_MINFLT),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,0,0,0,0) }, },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,0,0,0,0) }, },
     /* acct.psinfo.majflt */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_MAJFLT),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
     /* acct.psinfo.swaps */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_SWAPS),
-      PM_TYPE_U32, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
+      PM_TYPE_U64, ACCT_INDOM, PM_SEM_COUNTER, PMDA_PMUNITS(0,0,1,0,0,PM_COUNT_ONE) } },
 
     /* acct.id.uid */
     { NULL, { PMDA_PMID(CLUSTER_ACCT,ACCT_UID),
```

**Comment by natoscott** [comment]
> [...]
> I used float for etime because ac_etime field of struct acct_v3 is declared as float. However, as you commented, I think all three values (etime, utime, stime) should be floating values. I found my mistake. comp_t type is encoded by encode_comp_t function in linux kernel. It should be decoded when we read acct_v3. I paste a draft of a fix in the bottom of this comment. Could you review it?

Looks good!  I also had been looking at the v2 structure in acct(5) man page, I missed that I needed to scroll down to see the float in v3.

> By the way, is PM_SEM_COUNTER in the following code appropriate? pmval does not show non-zero value for utime or stime if PM_SEM_COUNTER is used.

I think so - this follows the equivalent metrics in the proc.* metrics (e.g. proc.psinfo.utime).  Its a cumulative count of time spent by the process executing user code.  pmval does rate convesion on counters, so I'd expect it would show non-zero only during samples where the value changes.  One can use the -r/--raw option to pmval to get see the non-rate converted value.

> [...]
> draft of a fix:

Looks good @shogo-matsumoto - I'll merge that shortly.

One additional issue I've just realised exists is that we are now enabling process accounting for every PCP installation when it may not have been enabled before.  This is not good, as it incurs an overhead for everyone - and plenty of people wont use these particular metrics, but still incur these overheads.

We'll need to take one of several approaches there I think - which do you think best?

- only enable (acct_init) process accounting once a client tool asks for one of the metrics.  we can disable accounting when all clients accessing the metrics if we track all of the connected clients accessing acct.*

- move the code into a new pmdaacct(1) which is not default installed.

- require an explicit pmStore(3) / pmstore(1) to enable and disable accounting - adding acct.control.* metrics along the lines of the proc.control.* metrics.

**Comment by shogo-matsumoto** [comment]
@natoscott 

>pmval does rate convesion on counters, so I'd expect it would show non-zero only during samples where the value changes.

Ok, I understand.

>We'll need to take one of several approaches there I think - which do you think best?

I think it may be best to move the code into a new pmdaacct, but it will take some time if I do that.  I made a PR (https://github.com/performancecopilot/pcp/pull/984) as a (temporarily) workaround which has a flag acct.control.enable_acct to control enable/disable of acct. As default it will prevent pmdaproc from creating private acct file (/var/lib/pcp/tmp/pmcd/pacct) and from calling acct. Note that access to system acct file (/var/account/pacct) is not restricted by the flag because other process is responsible for managing the file. Is the fix acceptable?

**Comment by natoscott** [comment]
@shogo-matsumoto that's fine - I think the store-based approach is probably the best actually.

I realised after my previous post that there's some code shared with other parts of pmdaproc that wouldn't be easy to extract (like the gid/uid name caches).

I've updated the test to exercise the new code and made a small fix to the fetch return code status.  I noticed there's no help text for the new metrics you added - could you add a little writeup for each? - e.g.

```
$ pminfo -t acct.control
acct.control.open_retry_interval [Interval of failed acct file opening check]
acct.control.check_acct_interval [Interval on which acct file size is checked]
acct.control.file_size_threshold [Size at which the acct file will be reopened]
acct.control.lifetime One-line Help: Error: One-line or help text is not available
acct.control.refresh One-line Help: Error: One-line or help text is not available
acct.control.enable_acct One-line Help: Error: One-line or help text is not available
```

**Comment by shogo-matsumoto** [comment]
@natoscott 

>I noticed there's no help text for the new metrics you added - could you add a little writeup for each? - e.g.

Sorry that I forgot to add help text. I made a PR(https://github.com/performancecopilot/pcp/pull/995). Thank you for helping me with testing and so on.

**Comment by natoscott** [comment]
> @natoscott
> 
> > I noticed there's no help text for the new metrics you added - could you add a little writeup for each? - e.g.
> 
> Sorry that I forgot to add help text. I made a PR(#995). Thank you for helping me with testing and so on.

No problem at all.  I think we're finished from the PMDA side of things now!

**Pull request merged**
