### PR TITLE
pmdastatsd: generate man page from pod

### PR DESCRIPTION
**Pull request by lzap**
This stops the insanity of maintaining man page.

### CODE REVIEW

**Comment by natoscott** [comment]
@lzap there's some possible down-sides here, e.g. this man page will no longer appear on online resources like pcp.io and man7.org (due to the way they're built) ... is it worth it?  Up to you and @Erbenos

**Comment by lzap** [comment]
Damn, it was painful to convert it back and I can hardly asses how painful it was to write it directly.

Here is an alternative proposal - an extra target that generates it manually so we would commit the generated `.1` file into git with some comment the file was autogenerated so people won't accidentaly change it.

If you agree I will refactor this.

**Comment by Erbenos** [comment]
I am actually doing some doc changes in my fork and since that one still has no pod doc files, can we wait with this, until .1 doc is merged with my version?

**Comment by lzap** [comment]
Of course, this is not important. If you prefer to maintain `.1` file manually I can also just throw this away.

**Pull request closed without merging**
