### PR TITLE
pmlogger scripts: move zeroconf definitions to read-only location

### PR DESCRIPTION
**Pull request by natoscott**
Follow up on suggestion in #1462 and relocate the zeroconf primary
logger default sampling interval setting to a read-only location.
This file does not belong in any user-configurable location - the
clue is in the name '*zero*conf' - it's not *some*conf. ;-)  This
is a more FHS-compliant location for this file and makes it very,
very clear this is not a file that should ever be edited.

### CODE REVIEW

**Comment by goodwinos** [comment]
Just a note - some user wants everything in pcp-zeroconf, EXCEPT they want to change PMLOGGER_INTERVAL? e.g. in the integration lab where they have -t 3s because 10s was not frequent enough. I guess they'll just have to edit the control file to and add -t3 to override .. that's three different files in three different directories (not counting the config file itself), specifying the default interval.

**Comment by natoscott** [comment]
> Just a note - some user wants everything in pcp-zeroconf, EXCEPT they want to change PMLOGGER_INTERVAL?

Then zeroconf is not for them - its **zero**conf for good reason.

**Comment by goodwinos** [comment]
there are ~ 2 dozen other files in the pcp-zeroconf package installed below /etc or /var. Some of them even marked as config files .. bit of a can of worms here

```
$ rpm -qlvV pcp-zeroconf
.........    /etc/pcp/pmieconf/zeroconf
.........  c /etc/pcp/pmieconf/zeroconf/all_threads
.........    /etc/pcp/pmlogconf/zeroconf
.........  c /etc/pcp/pmlogconf/zeroconf/atop-proc
.........  c /etc/pcp/pmlogconf/zeroconf/interrupts
.........  c /etc/pcp/pmlogconf/zeroconf/nfsclient
.........  c /etc/pcp/pmlogconf/zeroconf/numastat
.........  c /etc/pcp/pmlogconf/zeroconf/pidstat
.........  c /etc/pcp/pmlogconf/zeroconf/pidstat-summary
.........  c /etc/pcp/pmlogconf/zeroconf/tapestat
.........  c /etc/pcp/pmlogconf/zeroconf/xfs-perdev
.........  c /etc/sysconfig/pmlogger_zeroconf
.........    /usr/lib/systemd/system/pmlogger_daily_report.service
.........    /usr/lib/systemd/system/pmlogger_daily_report.timer
.........    /usr/lib/tmpfiles.d/pcp-zeroconf.conf
.........    /usr/libexec/pcp/bin/pmlogger_daily_report
.........    /var/lib/pcp/config/pmieconf/zeroconf
.........    /var/lib/pcp/config/pmieconf/zeroconf/all_threads
.........    /var/lib/pcp/config/pmlogconf/zeroconf
.........    /var/lib/pcp/config/pmlogconf/zeroconf/atop-proc
.........    /var/lib/pcp/config/pmlogconf/zeroconf/interrupts
.........    /var/lib/pcp/config/pmlogconf/zeroconf/nfsclient
.........    /var/lib/pcp/config/pmlogconf/zeroconf/numastat
.........    /var/lib/pcp/config/pmlogconf/zeroconf/pidstat
.........    /var/lib/pcp/config/pmlogconf/zeroconf/pidstat-summary
.........    /var/lib/pcp/config/pmlogconf/zeroconf/tapestat
.........    /var/lib/pcp/config/pmlogconf/zeroconf/xfs-perdev
.........    /var/log/pcp/sa
```

**Comment by natoscott** [comment]
There's no new issue there - pmlogconf and pmieconf are using historical locations - there's no alternative (yet) that zeroconf could use.  In both of those cases, /usr/share would be a more correct location however, and we should plan a transition in due course.

**Comment by natoscott** [comment]
Merged.

**Pull request closed without merging**
