### PR TITLE
pmdabpf valgrind tests

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
depends on #1445

### CODE REVIEW

**Comment by andreasgerstmayr** [comment]
blocked on https://bugs.kde.org/show_bug.cgi?id=451626

There's one other issue: The `pminfo -L -K clear -K add,157,$PCP_PMDAS_DIR/bpf/pmda_bpf,bpf_init` magic runs `bpf_init()` and then immediately fetches the metric values, right? Sometimes the biolatency module (which collects the latency of block I/O requests) didn't gather any requests in that short timeframe. Is there any way to run some command (`dd` to get some I/O activity) or wait a bit before fetching the values?

**Comment by natoscott** [comment]
> There's one other issue: The `pminfo -L -K clear -K add,157,$PCP_PMDAS_DIR/bpf/pmda_bpf,bpf_init` magic runs `bpf_init()` and then immediately fetches the metric values, right?

Yep.  pmNewContext(3) does the bpf_init from memory, and pmFetch(3) does the sampling - but all within pminfo.

> Sometimes the biolatency module (which collects the latency of block I/O requests) didn't gather any requests in that short timeframe. Is there any way to run some command (`dd` to get some I/O activity) or wait a bit before fetching the values?

Not using pminfo - I think you'd need a custom tool that uses local context with a delay.  Or maybe use pmval?  It will still see the uninitialized metrics on first fetch, but subsequent samples should come good.  Doesn't do all of what pminfo does though, so maybe a little qa/src utility is needed, not sure.

| Ideally still keep exercising the DSO part of the bpf PMDA under valgrind.

+1

**Comment by andreasgerstmayr** [comment]
> Or maybe use pmval? It will still see the uninitialized metrics on first fetch, but subsequent samples should come good. Doesn't do all of what pminfo does though, so maybe a little qa/src utility is needed, not sure.

Ah, great idea! I didn't realize pmval also supports `-K`. Yep, that works. Perfect :)

**Comment by andreasgerstmayr** [comment]
I've created `qa/src/wait_for_values.c` now, because it's too messy to filter pmval output which is interweaved with valgrind output.
This tool waits up to X milliseconds to fetch any non-zero value, and sleeps 100ms if no value was found.

**Pull request merged**
