### PR TITLE
pmdabcc: label support

### PR DESCRIPTION
**Pull request by andihit**

### CODE REVIEW

**Comment by myllynen** [comment]
Also, please make sure pylint runs cleanly (methods need comments at least) and prefer to keep coding style consistent (%s instead of format() and "return {}" instead "return '{}'" if possible). Thanks.

**Comment by andihit** [comment]
sry about the pylint/PEP, I'll add a check to travis

**Comment by andihit** [comment]
I've updated the branch to reflect the changes
I'll create a separate PR for including pylint into travis as I have to update a few other files as well to not break the build immediately

**Comment by myllynen** [comment]
LGTM, thanks! (As pointed out, the methods need to return strings not dicts.)

**Pull request merged**
